version: "3.7"

services:
  test:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
      args:
        REQUIREMENTS: test
        DJANGO_SETTINGS_MODULE: {{ cookiecutter.django_project_name }}.settings_test
    entrypoint: /app/test-entrypoint.sh
    env_file:
      - .env-test
    environment:
      DJANGO_DEBUG:
      DJANGO_DEBUG_SQL:
      PYTHONHUNTER:
      PYTHONHUNTERCONFIG:
      SERVER_NAME: localhost
      DJANGO_SECRET_KEY: test123
      SENTRY_DSN: ""
    stop_signal: SIGINT
    depends_on:
      - pg
    volumes:
      - $PWD:/app
      - $PWD/.home:/home/app
